apiVersion: v1
kind: Secret
metadata:
    name: {{ printf "%s-secret" .Values.microservice.name }}
    namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
    POSTGRES_DB: {{ .Values.env.POSTGRES_DB | b64enc }}
    POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc }}
    POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc }}