apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.microservice.name }}
              port:
                number: {{ .Values.workload.port }}
