apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.microservice.name }}
    namespace: {{ .Values.microservice.namespace }}
spec:
    selector:
        app: {{ .Values.microservice.name }}
    ports:
    - port: {{ .Values.workload.port }}
      targetPort: {{ .Values.workload.port }}